author="fzerorubigd<fzero@rubi.gd>"
version="1"
description="A full-featured & carefully designed adaptive prompt for Bash & Zsh"
[install]
	[install.repo]
		# Installation repository. currently only support git repository
		type= "git"
		# Address of the repository
		address="https://github.com/nojhan/liquidprompt.git"
		# Target directory. if omit this the target is $ZACMAN_ROOT/${ZACMAN_NAME} and exported as ${ZACMAN_TARGET} in all
		# installation scripts
		target="~/.liquidprompt"
		# Checkout after install?
		checkout = "master"
	[install.zsh]
		# List of files to source in the generated zshrc file, relative to ZACMAN_TARGET
		source=["liquidprompt"]
		# List of path to add to fpath folder
		fpath=[]
		# Load this only in interactive shels
		interactive = true
		
