author="fzerorubigd<fzero@rubi.gd>"
version="1"
description="Some simple configuration for zsh extracted from oh-my-zsh and other"
[install]
	[install.repo]
		# Installation repository. currently only support git repository
		type= "git"
		# Address of the repository
		address="https://github.com/fzerorubigd/zsh-must.git"
		# Target directory. if omit this the target is $ZACMAN_ROOT/${ZACMAN_NAME} and exported as ${ZACMAN_TARGET} in all
		# installation scripts
		# Checkout after install?
		checkout = "master"
	[install.zsh]
		# List of files to source in the generated zshrc file, relative to ZACMAN_TARGET
		source=["completion.zsh", "correction.zsh", "directories.zsh", "history.zsh", "key-bindings.zsh" , "misc.zsh"]
		# List of path to add to fpath folder
		fpath=[""]
		# Load this only in interactive shells default false
		interactive = false
		
